hydra:
  run:
    dir: evaluations/${model.name}/${now:%Y-%m-%d_%H%M%S}

gt_path: /home/aircraft-lab/Documents/gt_tracks
running_locally: False


weights_path: /home/aircraft-lab/Documents/Deep_Learning_Project/DL_Final_Project_Team6/DL_Final_Project_Team6/pretrained_weights/weights_finetuned_ec.ckpt

track_name: shitomasi_custom_v5
representation: time_surfaces_v2_5
patch_size: 31
visualize: False
dt_track_vis: 0.2

# Composing nested config with default
defaults:
  - model: correlation3_unscaled
# Pytorch lightning trainer's argument
trainer:
  gpus: [0]
