# @package _global_

checkpoint_path: '/home/aircraft-lab/Documents/Deep_Learning_Project/DL_Final_Project_Team6/DL_Final_Project_Team6/training_runs/mf/correlation3_unscaled/open_source/2024-11-18_112319/checkpoints/pretrained_weights.zip'
init_unrolls: 8
max_unrolls: 8
unroll_factor: 8
unroll_schedule: [200]
